return {
  { "rebelot/kanagawa.nvim", lazy = true },
  { "rose-pine/neovim", lazy = true },
  { "EdenEast/nightfox.nvim", lazy = true },
  { "navarasu/onedark.nvim", lazy = true },
  { "projekt0n/github-nvim-theme", lazy = true },
  { "sainnhe/everforest", lazy = true },
  { "Mofiqul/vscode.nvim", lazy = true },
  { "scottmckendry/cyberdream.nvim", lazy = true },
  { "olimorris/onedarkpro.nvim", lazy = true },
  { "marko-cerovac/material.nvim", lazy = true },
  { "Mofiqul/dracula.nvim", lazy = true },
  { "Mofiqul/adwaita.nvim", lazy = true },
  { "nyoom-engineering/oxocarbon.nvim", lazy = true },
  { "craftzdog/solarized-osaka.nvim", lazy = true },
  { "sainnhe/sonokai", lazy = true },
  { "AlexvZyl/nordic.nvim", lazy = true },
  { "bluz71/vim-moonfly-colors", lazy = true },
  { "sainnhe/edge", lazy = true },
  { "tiagovla/tokyodark.nvim", lazy = true },
  { "ribru17/bamboo.nvim", lazy = true },
  { "savq/melange-nvim", lazy = true },
  { "eldritch-theme/eldritch.nvim", lazy = true },
  { "bluz71/vim-nightfly-colors", lazy = true },
  { "rmehri01/onenord.nvim", lazy = true },
  { "folke/tokyonight.nvim", lazy = true },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin",
    },
  },
}